_BASE_: zero_shot_maskformer_R50_bs16_20k.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
  CLIP_ADAPTER:
    
    SEPERATE_ADAPTER: False

INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 16)]"]
OUTPUT_DIR: "prompt/output_voc/R101c_learned_prompt_bs32_20k_1"
